### ISSUE TITLE
Implement / bind non-blocking API (portaudio callback)

### ISSUE THREAD

**Issue by jeremyletang** [jeremyletang/rust-portaudio#21]
Portaudio provide a non-blocking `API` using callback function which is called each time some new data are coming. For now this functionality is not implemented in rust-portaudio as a user can do the same thing using a rust task and calling the blocking api inside of it.
Maybe we  can bind this functionality too as the native implementation is probably more effective.

**Comment by safiire** [comment]
Is this project still active?  Is there some problem with exposing the callback in Rust?

**Comment by mitchmindtree** [comment]
@safiire Yep! I think it's not implemented yet just because no one has had a chance to do it yet or needed it enough - most people who need a non-blocking audio thread seem to just spawn a separate thread and run the blocking instance on that. Would be nice to have this implemented at some point though, shouldn't be that tricky at all.

**Comment by safiire** [comment]
Ahh, cool, ok thanks for the response :)

**Comment by killkrt** [comment]
It would be great having callback mechanism. Blocking could cause a lot of unwanted latency. Is there any estimation about when it will be implemented? I mean it's something that it will happen by weeks, months or maybe?

Thanks for your great job!

**Comment by mitchmindtree** [comment]
@jeremyletang @smosher @safiire @killkrt done! See #68 for the PR, or check out [the example](https://github.com/jeremyletang/rust-portaudio/blob/master/examples/non_blocking.rs#L89).

**Comment by safiire** [comment]
Woo, thanks :)
