### ISSUE TITLE
Rust-portaudio crashes (doesn't panic) with "signal 11"

### ISSUE THREAD

**Issue by golddranks** [jeremyletang/rust-portaudio#59]
I started a project that uses rust-portaudio. The example provided in this repo seems to work, but when I try to generate and play a generated sound wave by myself, I run all kinds of strange phenomena.

My code is in https://github.com/golddranks/ongen

First of all, trying to pass it just a buffer of zeros, it emits loud buzzing noise. (With buffer of 0.00s, it should be just silent, right?) I thought this was maybe problem in latency and the output stream was starving, and thus producing clicks whenever the buffer was consumed and a new buffer was provided. I set the latency looser, `default_high_output_latency`, with no audible difference.

Then I tried to set the `frames_per_buffer` value higher. Originally I had it in 256 like in the example. Changing the buffer size to 512 produced audible difference, but still just noise, all together. When I set it to 1024, Portaudio started crashing, not panicking in Rust-style but like this: `Process didn't exit successfully: `target/ongen` (signal: 11)`

Do you have any idea how to fix these issues? It is surely the C library side that crashes with "signal 11"? Is buffer of 1024 outrageous in size? Any idea how to fix the buzzing?

Running on OS X, 
`rustc 1.0.0-nightly (3b3bb0e68 2015-03-04) (built 2015-03-04)`, 
```
PortAudio host name : Core Audio
Default output device name : Built-in Output
```

**Comment by golddranks** [comment]
Btw. In the example there is the call `stream.get_stream_write_available()`. It seems to return immediately, and according to the docstrings `stream.write()` blocks. Is `stream.write()` safe to call already when `stream.get_stream_write_available()` returns Result(None)? The example seems to busy-loop until `stream.get_stream_write_available()` returns something. Is that neccessary?

**Comment by mitchmindtree** [comment]
@golddranks `get_stream_write_available()` [returns the number of frames currently available for writing](https://github.com/jeremyletang/rust-portaudio/blob/master/src/pa/mod.rs#L540). If it returns Ok(None), then that means the query was successful (hence `Ok`) but there are no frames available for writing (hence `None`). You'll have to wait for `get_stream_write_available()` to return `Ok(Some(_))` before writing, otherwise it will be sure to return some kind of strange behaviour / error. The reason you have to wait is because the stream is real-time and the buffers must be fed to the device at a very specific rate (determined by sample rate and buffer size). The rate is often extremely fast - it can be risky to sleep as a result, this is why the example busy loops while waiting.

Out of curiosity, have you checked out the [sound_stream](https://github.com/RustAudio/sound_stream) crate? It's a safe/simple wrapper over rust-portaudio that takes care of most of this stuff for you in a more rust-esque manner. However it is currently a little limited in functionality (you currently can't choose a device other than the default, for example, though this will change soon).

Anyway, hope this helps!

**Comment by golddranks** [comment]
What if the amount of frames available for writing is smaller than `frames_per_buffer `? Should it busyloop until the number is larger, or until there's just some more than 0? I was thinking that since `write()` is blocking, maybe it would block automatically until there was space to write the current buffer. Regardless, I busy-loop like it does in the example, but it still doesn't work...

**Comment by golddranks** [comment]
Oh, by the way, it says this in the docstrings: "Retrieve the number of frames that can be written to the stream without waiting." This sounds like it still would be possible to call `write()`, if waiting is okay. Is this right? If `write()` can't simply be called when `get_stream_write_available()` returns `None`, it would be good to state it more clearly.

**Comment by mitchmindtree** [comment]
@golddranks I've personally never had `get_stream_write_available()` return a number of frames that is different to the buffer size - I doubt your problem is related to this (I'm sure if you print it, it will be equivalent to the number of frames in a buffer).

I just had a look through your code and it seems that you're not taking into account that the buffer is interleaved. By this I mean that the buffer you give to `write` must be FRAMES * num_channels (in your case, [you've given `2` channels](https://github.com/golddranks/ongen/blob/master/src/main.rs#L36)) in length, where the buffer is structured like this:

```
[Left 0, Right 0, L1, R1, L2, R2, L3, R3, ..... L FRAMES, R FRAMES]
```

So the start of your `fn main()` should be more like this:
```Rust
let buffer : &mut [f32] = &mut [0.0; FRAMES * 2][..];
    
for frame in buffer.chunks_mut(2) {
    for channel in frame.iter_mut() {
        *channel = 0.00;
    }
}

...
```

The reason it's making strange noises is probably because the last half of the buffer is uninitialised memory (as it hasn't been written to). Hopefully this should fix it!

**Comment by golddranks** [comment]
Ah, that certainly explains it! Thank you. I'll try this as soon as I can.

**Comment by golddranks** [comment]
Thanks, that solved this.

**Comment by golddranks** [comment]
Btw. one more thing: "To write audio data to a Stream call Pa_WriteStream() and to read data call Pa_ReadStream(). These functions will block if the internal buffers are full, making them safe to call in a tight loop. If you want to avoid blocking you can query the amount of available read or write space using Pa_GetStreamReadAvailable() or Pa_GetStreamWriteAvailable() and use the returned values to limit the amount of data you read or write."

So the blocking calls are essentially safe, and calling the available functions is, thus, optional. (Although it wastes time on blocking, if there's something better to do. But if there isn't, why continue polling, when you can just leave it to the library anyway.)
